# Generating Random Numbers with Numpty

NumPy is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

NumPy provides various routines in the submodule random. It uses a particular algorithm, called the Mersenne Twister, to generate pseudorandom numbers.

First import numpy as seen below, the imported numpy package will come with the random submodule.

In [1]:
import numpy as np

Now we want to do something with this package. np.random.uniform draws samples from a uniform distribution. 
The code below is the same as numpy.random.uniform(low=0.0, high=1.0). We are giving it a range and it will return as output a random number in that range with a lowest possible selection and a highest possible selection.

In [2]:
np.random.uniform(0.0, 100.0)

78.76789298539285

The random number has been generated. The answer should be different each time it is run because the range is big enough that it is very unlikey you would get the same number twice.

#####  Arrange and reshape

Arrange : Return evenly spaced values within a given interval.  
Reshape : Gives a new shape to an array without changing its data.

So below we are setting an array to display 15 values and then using reshape to display it in a 3 x 5 format, 3 columns and 5 rows. Then we print out the array by calling it.

In [3]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

###### Shuffle

Modify a sequence in-place by shuffling its contents.  

This function only shuffles the array along the first axis of a multi-dimensional array. The order of sub-arrays is changed but their contents remains the same.

So we can take our array from above and shuffle the order of the rows. Although the rows are shuffled their order remains the same inside the row because it is only works on the first axis.

In [4]:
a2 = np.arange(15).reshape(3, 5)
np.random.shuffle(a2)
a2

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4]])

If we don't use reshape to change the way the array is ouput we'll see a full random array

In [5]:
a3 = np.arange(15)
np.random.shuffle(a3)
a3

array([ 0, 12,  4,  2,  5, 13, 11,  9, 14,  8,  6, 10,  1,  3,  7])