# Generating Random Numbers with Numpty

NumPy is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

NumPy provides various routines in the submodule random. It uses a particular algorithm, called the Mersenne Twister, to generate pseudorandom numbers.

First import numpy as seen below, the imported numpy package will come with the random submodule.

In [1]:
import numpy as np

Now we want to do something with this package. np.random.uniform draws samples from a uniform distribution. 
The code below is the same as numpy.random.uniform(low=0.0, high=1.0). We are giving it a range and it will return as output a random number in that range with a lowest possible selection and a highest possible selection.

In [2]:
np.random.uniform(0.0, 100.0)

20.56175072019912

The random number has been generated. The answer should be different each time it is run because the range is big enough that it is very unlikey you would get the same number twice.

### Randint

Return random integers from low (inclusive) to high (exclusive). This can be useful in a situation like simulating the roll of a dice. Give randint the rang 1 and 7 because the first parameter is inclusive and the second exclusive, so 1 upto 7. 

In [3]:
for i in range (10):
    print (np.random.randint(1,7))

2
3
6
1
5
4
6
5
1
2


###  Arrange and reshape

Arrange : Return evenly spaced values within a given interval.  
Reshape : Gives a new shape to an array without changing its data.

So below we are setting an array to display 15 values and then using reshape to display it in a 3 x 5 format, 3 columns and 5 rows. Then we print out the array by calling it.

In [4]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### Shuffle

Modify a sequence in-place by shuffling its contents.  

This function only shuffles the array along the first axis of a multi-dimensional array. The order of sub-arrays is changed but their contents remains the same.

So when we take our array from above and shuffle the order of the rows. Although the rows are shuffled their order remains the same inside the row because it is only works on the first axis.

In [5]:
a2 = np.arange(15).reshape(3, 5)
np.random.shuffle(a2)
a2

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9]])

If we don't use reshape to change the way the array is ouput we'll see a full random array

In [6]:
a3 = np.arange(15)
np.random.shuffle(a3)
a3

array([13,  2,  5,  3, 10, 11,  6,  7,  8, 14, 12,  1,  9,  0,  4])

### Seed

Seed the generator. This method is called when RandomState is initialized. It can be called again to re-seed the generator

In [7]:
np.random.seed(1234)
np.random.uniform(0, 10, 5)

array([1.9151945 , 6.22108771, 4.37727739, 7.85358584, 7.79975808])

### RandomState

RandomState exposes a number of methods for generating random numbers drawn from a variety of probability distributions. In addition to the distribution-specific arguments, each method takes a keyword argument size that defaults to None. If size is None, then a single value is generated and returned. If size is an integer, then a 1-D array filled with generated values is returned. If size is a tuple, then an array with that shape is filled and returned.

A fixed seed and a fixed series of calls to ‘RandomState’ methods using the same parameters will always produce the same results so the random answer can be worked out if the user knows the seed.

In [8]:
r = np.random.RandomState(1234)
r.uniform(0, 10, 5)

array([1.9151945 , 6.22108771, 4.37727739, 7.85358584, 7.79975808])